---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: cert-manager

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/component: cert-manager
  team: devops

resources:
  - apiservice.yaml
  - deployment.yaml
  - pki.yaml
  - rbac.yaml
  - service.yaml
  - serviceaccount.yaml
  - validating-webhook.yaml
