---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: cert-manager

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/component: cert-manager
  team: devops

bases:
  - ../base/cainjector
  - ../base/webhook

resources:
  - deployment.yaml
  - namespace.yaml
  - rbac.yaml
  - serviceaccount.yaml
