---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/component: cert-manager
  team: devops

bases:
  - base

resources:
  - crds.yaml
